/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vg.scfc.financing.cis.ui.panel;

import com.vg.commons.dlg.WaitSplashScreen;
import com.vg.commons.listener.DoJasperPrintReport;
import com.vg.scfc.financing.cis.ui.controller.ReportController;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author rodel
 */
public class CAFReportPanel extends javax.swing.JPanel implements DoJasperPrintReport {

    /**
     * Creates new form CAFReportPanel
     */
    public CAFReportPanel() {
        initComponents();
        initOptionGroup();
    }

    private void initOptionGroup() {
        optionGroup.add(optionFront);
        optionGroup.add(optionBack);
        optionGroup.add(optionCM1);
        optionGroup.add(optionCM2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionGroup = new javax.swing.ButtonGroup();
        optionFront = new javax.swing.JRadioButton();
        optionBack = new javax.swing.JRadioButton();
        optionCM1 = new javax.swing.JRadioButton();
        optionCM2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrint = new javax.swing.JButton();

        optionFront.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        optionFront.setSelected(true);
        optionFront.setText("Front Page");

        optionBack.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        optionBack.setText("Back Page");

        optionCM1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        optionCM1.setText("Co-Maker 1");

        optionCM2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        optionCM2.setText("Co-Maker 2");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optionFront)
                            .addComponent(optionBack)
                            .addComponent(optionCM1)
                            .addComponent(optionCM2))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionFront)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionCM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionCM2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        new WaitSplashScreen(null, true, this, "CREDIT APPLICATION FORM").getThisDlg();
    }//GEN-LAST:event_btnPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton optionBack;
    private javax.swing.JRadioButton optionCM1;
    private javax.swing.JRadioButton optionCM2;
    private javax.swing.JRadioButton optionFront;
    private javax.swing.ButtonGroup optionGroup;
    // End of variables declaration//GEN-END:variables
    private String formNo;

    public void setFormNo(String formNo) {
        this.formNo = formNo;
    }

    public void enableCM2(boolean value) {
        optionCM2.setEnabled(value);
    }

    @Override
    public JasperPrint printNow() throws Exception {
        JasperPrint jasperPrint = null;
        if (optionFront.isSelected()) {
            jasperPrint = ReportController.getInstance().print(formNo, 1, "");
        } else if (optionBack.isSelected()) {
            jasperPrint = ReportController.getInstance().print(formNo, 2, "");
        } else if (optionCM1.isSelected()) {
            jasperPrint = ReportController.getInstance().print(formNo, 3, "CM1");
        } else if (optionCM2.isSelected()) {
            jasperPrint = ReportController.getInstance().print(formNo, 4, "CM2");
        }

        if (jasperPrint == null) {
            throw new Exception();
        } else {
            return jasperPrint;
        }
    }

}
