/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vg.scfc.financing.cis.ui.panel;

import com.vg.commons.util.DateUtil;
import com.vg.scfc.financing.cis.ent.Company;
import com.vg.scfc.financing.cis.ui.controller.CompanyController;
import com.vg.scfc.financing.cis.ui.validator.UIValidator;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rodel
 */
public class CompanyInformationPanel extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form CompanyInformationPanel
     */
    public CompanyInformationPanel() {
        initComponents();
        initKeyListener();
    }

    private void initKeyListener() {
        txtOwnerPresident.addKeyListener(this);
        txtOfficeAddress.addKeyListener(this);
        txtBusinessNature.addKeyListener(this);
        txtYearsOfOperation.addKeyListener(this);
        txtContact.addKeyListener(this);
        txtTIN.addKeyListener(this);
        txtEmail.addKeyListener(this);
        txtBussPermitNo.addKeyListener(this);
        txtIssuedDate.addKeyListener(this);
        txtExpireDate.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtOwnerPresident = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOfficeAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBusinessNature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYearsOfOperation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTIN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBussPermitNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        try {
            txtIssuedDate = new com.vg.commons.formattedfields.FormattedSimpleDateField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        try {
            txtExpireDate = new com.vg.commons.formattedfields.FormattedSimpleDateField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Owner/President");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        txtOwnerPresident.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtOwnerPresident.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOwnerPresidentFocusLost(evt);
            }
        });
        add(txtOwnerPresident, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 5, 255, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Office Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 35, -1, -1));

        txtOfficeAddress.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        add(txtOfficeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 30, 535, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Nature of Buss.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        txtBusinessNature.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtBusinessNature.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusinessNatureFocusLost(evt);
            }
        });
        add(txtBusinessNature, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 55, 255, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Years of Operation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        txtYearsOfOperation.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtYearsOfOperation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearsOfOperationFocusLost(evt);
            }
        });
        add(txtYearsOfOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 55, 145, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Contact #");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        txtContact.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactFocusLost(evt);
            }
        });
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 80, 120, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("T.I.N.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 85, -1, -1));

        txtTIN.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtTIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTINFocusLost(evt);
            }
        });
        add(txtTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 80, 140, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("E-mail");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 85, -1, -1));

        txtEmail.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 170, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Buss. Permit #");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        txtBussPermitNo.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtBussPermitNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBussPermitNoFocusLost(evt);
            }
        });
        add(txtBussPermitNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 105, 150, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Issued on");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Expires On");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        txtIssuedDate.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtIssuedDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIssuedDateFocusLost(evt);
            }
        });
        add(txtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 105, 110, -1));

        txtExpireDate.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtExpireDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpireDateFocusLost(evt);
            }
        });
        add(txtExpireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 105, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (!txtEmail.getText().equals("")) {
            email = UIValidator.isValidEmail(txtEmail);
        } else {
            email = "";
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtOwnerPresidentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOwnerPresidentFocusLost
        president = UIValidator.validate(txtOwnerPresident);
    }//GEN-LAST:event_txtOwnerPresidentFocusLost

    private void txtBusinessNatureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusinessNatureFocusLost
        natureOfBusiness = UIValidator.validate(txtBusinessNature);
    }//GEN-LAST:event_txtBusinessNatureFocusLost

    private void txtYearsOfOperationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearsOfOperationFocusLost
        yearsInOperation = Integer.parseInt(UIValidator.isNumeric(txtYearsOfOperation));
    }//GEN-LAST:event_txtYearsOfOperationFocusLost

    private void txtContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactFocusLost
        contactNo = UIValidator.isNumeric(txtContact);
    }//GEN-LAST:event_txtContactFocusLost

    private void txtTINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTINFocusLost
        tin = UIValidator.isNumeric(txtTIN);
    }//GEN-LAST:event_txtTINFocusLost

    private void txtBussPermitNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBussPermitNoFocusLost
        businessPermit = UIValidator.isNumeric(txtBussPermitNo);
    }//GEN-LAST:event_txtBussPermitNoFocusLost

    private void txtIssuedDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIssuedDateFocusLost
        try {
            issuedDate = txtIssuedDate.getDate();
        } catch (ParseException ex) {
            UIValidator.log(ex, CompanyInformationPanel.class);
        }
    }//GEN-LAST:event_txtIssuedDateFocusLost

    private void txtExpireDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpireDateFocusLost
        try {
            expirationDate = txtExpireDate.getDate();
        } catch (ParseException ex) {
            UIValidator.log(ex, CompanyInformationPanel.class);
        }
    }//GEN-LAST:event_txtExpireDateFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBusinessNature;
    private javax.swing.JTextField txtBussPermitNo;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private com.vg.commons.formattedfields.FormattedSimpleDateField txtExpireDate;
    private com.vg.commons.formattedfields.FormattedSimpleDateField txtIssuedDate;
    private javax.swing.JTextField txtOfficeAddress;
    private javax.swing.JTextField txtOwnerPresident;
    private javax.swing.JTextField txtTIN;
    private javax.swing.JTextField txtYearsOfOperation;
    // End of variables declaration//GEN-END:variables
    private String president;
    private String address;
    private String natureOfBusiness;
    private int yearsInOperation;
    private String contactNo;
    private String tin;
    private String email;
    private String businessPermit;
    private Date issuedDate;
    private Date expirationDate;
    private String formSeries;
    private Date applicationDate;
    private String companyName;
    private Company company;

    public void setCompany(Company company) {
        this.company = company;
        setCompany(company);
    }

    public void setFormSeries(String formSeries) {
        this.formSeries = formSeries;
    }

    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (txtOwnerPresident.isFocusOwner()) {
                txtOfficeAddress.requestFocus();
            } else if (txtOfficeAddress.isFocusOwner()) {
                txtBusinessNature.requestFocus();
            } else if (txtBusinessNature.isFocusOwner()) {
                txtYearsOfOperation.requestFocus();
            } else if (txtYearsOfOperation.isFocusOwner()) {
                txtContact.requestFocus();
            } else if (txtContact.isFocusOwner()) {
                txtTIN.requestFocus();
            } else if (txtTIN.isFocusOwner()) {
                txtEmail.requestFocus();
            } else if (txtEmail.isFocusOwner()) {
                txtBussPermitNo.requestFocus();
            } else if (txtBussPermitNo.isFocusOwner()) {
                txtIssuedDate.requestFocus();
            } else if (txtIssuedDate.isFocusOwner()) {
                txtExpireDate.requestFocus();
            }
                break;
            case KeyEvent.VK_UP:
                if (txtExpireDate.isFocusOwner()) {
                txtIssuedDate.requestFocus();
            } else if (txtIssuedDate.isFocusOwner()) {
                txtBussPermitNo.requestFocus();
            } else if (txtBussPermitNo.isFocusOwner()) {
                txtEmail.requestFocus();
            } else if (txtEmail.isFocusOwner()) {
                txtTIN.requestFocus();
            } else if (txtTIN.isFocusOwner()) {
                txtContact.requestFocus();
            } else if (txtContact.isFocusOwner()) {
                txtYearsOfOperation.requestFocus();
            } else if (txtYearsOfOperation.isFocusOwner()) {
                txtBusinessNature.requestFocus();
            } else if (txtBusinessNature.isFocusOwner()) {
                txtOfficeAddress.requestFocus();
            } else if (txtOfficeAddress.isFocusOwner()) {
                txtOwnerPresident.requestFocus();
            }
                break;
        }
    }

    public void setFieldsEditable(boolean value) {
        txtOwnerPresident.setEditable(value);
        txtOfficeAddress.setEditable(value);
        txtBusinessNature.setEditable(value);
        txtYearsOfOperation.setEditable(value);
        txtContact.setEditable(value);
        txtTIN.setEditable(value);
        txtEmail.setEditable(value);
        txtBussPermitNo.setEditable(value);
        txtIssuedDate.setEditable(value);
        txtIssuedDate.setEditable(value);
    }

    public void resetToDefault() {
        txtOwnerPresident.setText("");
        txtOfficeAddress.setText("");
        txtBusinessNature.setText("");
        txtYearsOfOperation.setText("");
        txtContact.setText("");
        txtTIN.setText("");
        txtEmail.setText("");
        txtBussPermitNo.setText("");
        txtIssuedDate.setText("");
        txtIssuedDate.setText("");
    }

    public void setCompanyInfo(Object o) {
        if (o == null) {
            resetToDefault();
        } else {
            Company c = (Company) o;
            txtOwnerPresident.setText(c.getPresident());
            txtOfficeAddress.setText(c.getAddress());
            txtBusinessNature.setText(c.getNatureOfBusiness());
            txtYearsOfOperation.setText(c.getYearOfService() + "");
            txtContact.setText(c.getContactNo());
            txtTIN.setText(c.getTin());
            txtEmail.setText(c.getEmail());
            txtBussPermitNo.setText(c.getBusinessPermitNo());
            txtIssuedDate.setText(DateUtil.toString(c.getIssuedDate(), "MM/HH/yyyy"));
            txtIssuedDate.setText(DateUtil.toString(c.getExpirationDate(), "MM/HH/yyyy"));
        }
    }

    public boolean saveCompanyInfo() {
        Object o = CompanyController.getInstance().createNew(president, address, natureOfBusiness, yearsInOperation, contactNo, tin, email, businessPermit, issuedDate, expirationDate, formSeries, applicationDate, companyName);
        setCompany((Company) o);
        return o != null;
    }

    public boolean updateCompanyInfo() {
        Object o = CompanyController.getInstance().update(company);
        setCompany((Company) o);
        return o != null;
    }
}
