/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vg.scfc.financing.cis.ui.panel;

import com.vg.scfc.financing.cis.ent.Customer;
import com.vg.scfc.financing.cis.ent.TransactionForm;
import com.vg.scfc.financing.cis.ui.controller.SearchController;
import com.vg.scfc.financing.cis.ui.validator.UIValidator;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author rodel
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        startUpSetUp();
    }

    private void startUpSetUp() {
        initCustomerTable();
        initTransactionFormTable();
        refreshCustomerTable(SearchController.getInstance().findAll());
    }

    private void initCustomerTable() {
        tblCustomer.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    selectedIndex = tblCustomer.getSelectedRow();
                    if (selectedIndex >= 0) {
                        Customer c = customers.get(selectedIndex);
                        if (c != null) {
                            setCustomer(c);
                        }
                    }
                } catch (Exception e) {
                    UIValidator.log(e, SearchPanel.class);
                }
            }
        });
    }

    private void initTransactionFormTable() {
        tblTransactionForm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblTransactionForm.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    selectedIndex = tblTransactionForm.getSelectedRow();
                    if (selectedIndex >= 0) {
                        TransactionForm f = transactionForms.get(selectedIndex);
                        if (f != null) {
                            setTransactionForm(f);
                        }
                    }
                } catch (Exception e) {
                    UIValidator.log(e, SearchPanel.class);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        customers = ObservableCollections.observableList(new LinkedList<Customer>());
        transactionForms = ObservableCollections.observableList(new LinkedList<TransactionForm>());
        txtUnitApplied = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransactionForm = new javax.swing.JTable();
        btnNewApplicant = new javax.swing.JButton();
        btnNewForm = new javax.swing.JButton();
        btnPrintVersion = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUnitApplied.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        txtUnitApplied.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnitAppliedFocusLost(evt);
            }
        });
        add(txtUnitApplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 250, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customers, tblCustomer);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${clientNo}"));
        columnBinding.setColumnName("Client #");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblCustomer);
        tblCustomer.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblCustomer.getColumnModel().getColumn(0).setMaxWidth(70);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, 250, 260));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, transactionForms, tblTransactionForm);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${txFormNo}"));
        columnBinding.setColumnName("Form #");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${txApplicationDate}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblTransactionForm);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 300, 250, 160));

        btnNewApplicant.setText("New Applicant");
        add(btnNewApplicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 470, 250, -1));

        btnNewForm.setText("New Form");
        add(btnNewForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 500, 250, -1));

        btnPrintVersion.setText("Print Version");
        add(btnPrintVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 530, 250, -1));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitAppliedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnitAppliedFocusLost
        txtUnitApplied.setText(UIValidator.validate(txtUnitApplied));
    }//GEN-LAST:event_txtUnitAppliedFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewApplicant;
    private javax.swing.JButton btnNewForm;
    private javax.swing.JButton btnPrintVersion;
    private java.util.List<Customer> customers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblTransactionForm;
    private java.util.List<TransactionForm> transactionForms;
    private javax.swing.JTextField txtUnitApplied;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private int selectedIndex = 0;
    private Customer customer;
    private TransactionForm transactionForm;

    public Customer getCustomer() {
        return customer;
    }

    public TransactionForm getTransactionForm() {
        return transactionForm;
    }

    public void setTransactionForm(TransactionForm transactionForm) {
        this.transactionForm = transactionForm;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;

        if (this.customer != null) {
            refreshTransactionFormTable(SearchController.getInstance().findByClientNo(this.customer.getClientNo()));
        }
    }

    public void refreshCustomerTable(List<Customer> c) {
        customers.clear();
        customers.addAll(c);
        if (!customers.isEmpty()) {
            tblCustomer.setRowSelectionInterval(0, 0);
        }
    }

    public void refreshTransactionFormTable(List<TransactionForm> t) {
        transactionForms.clear();
        transactionForms.addAll(t);
        if (!transactionForms.isEmpty()) {
            tblTransactionForm.setRowSelectionInterval(0, 0);
        }
    }
}
