/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vg.scfc.financing.cis.ui.panel;

import com.vg.commons.renderer.CustomTableCellRenderer;
import com.vg.commons.util.UIMgr;
import com.vg.scfc.financing.cis.ent.Customer;
import com.vg.scfc.financing.cis.ent.PersonalInfo;
import com.vg.scfc.financing.cis.ent.TransactionForm;
import com.vg.scfc.financing.cis.ui.controller.PersonalInfoController;
import com.vg.scfc.financing.cis.ui.controller.SearchController;
import com.vg.scfc.financing.cis.ui.dialog.CAFReportDlg;
import com.vg.scfc.financing.cis.ui.settings.UISetting;
import com.vg.scfc.financing.cis.ui.validator.UIValidator;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author rodel
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        startUpSetUp();
    }

    private void startUpSetUp() {
        initCustomerTable();
        initTransactionFormTable();
        txtSearch.putClientProperty("Quaqua.TextField.style", "search");
        txtSearch.setText("Search");
        policySetting();
        initSearchListener();
    }
    
    private void policySetting() {
//        UISetting.policy.addIndexedComponent(txtSearch);
//        UISetting.policy.addIndexedComponent(btnSearch);
        txtSearch.setFocusTraversalKeysEnabled(false);
    }
    
    private void initSearchListener() {
        txtSearch.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                switch(e.getKeyCode()) {
                    case KeyEvent.VK_ENTER:
                        refreshCustomerTable(SearchController.getInstance().findBySearchCriteriaLocationAndMode(txtSearch.getText(), UISetting.getStoreLocation().getFinStartCode(), 2));
                        break;
                }
            }
            
        });
    }

    private void initCustomerTable() {
        tblCustomer.putClientProperty("Quaqua.Table.style", "striped");
        tblCustomer.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCustomer.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    selectedIndex = tblCustomer.getSelectedRow();
                    if (selectedIndex >= 0) {
                        Customer c = customers.get(selectedIndex);
                        if (c != null) {
                            setCustomer(c);
                        }
                    }
                } catch (Exception e) {
                    UIValidator.log(e, SearchPanel.class);
                }
            }
        });
    }

    private void initTransactionFormTable() {
        tblTransactionForm.putClientProperty("Quaqua.Table.style", "striped");
        tblTransactionForm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblTransactionForm.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    selectedIndex = tblTransactionForm.getSelectedRow();
                    if (selectedIndex >= 0) {
                        TransactionForm f = transactionForms.get(selectedIndex);
                        if (f != null) {
                            setTransactionForm(f);
                        }
                    }
                } catch (Exception e) {
                    UIValidator.log(e, SearchPanel.class);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        customers = ObservableCollections.observableList(new LinkedList<Customer>());
        transactionForms = ObservableCollections.observableList(new LinkedList<TransactionForm>());
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransactionForm = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        lblRecordCount = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 150, -1));

        tblCustomer.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblCustomer.setRowHeight(19);
        tblCustomer.setRowMargin(2);
        tblCustomer.setShowHorizontalLines(false);
        tblCustomer.setShowVerticalLines(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customers, tblCustomer);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${clientNo}"));
        columnBinding.setColumnName("Client #");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblCustomer);
        tblCustomer.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblCustomer.getColumnModel().getColumn(0).setMaxWidth(70);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, 250, 340));

        tblTransactionForm.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblTransactionForm.setRowHeight(19);
        tblTransactionForm.setRowMargin(2);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, transactionForms, tblTransactionForm);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${txFormNo}"));
        columnBinding.setColumnName("Transaction #");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${txApplicationDate}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblTransactionForm);
        tblTransactionForm.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRenderer(new SimpleDateFormat("yyyy-MM-hh")));

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 380, 250, 160));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/printIcon2.png"))); // NOI18N
        btnPrint.setText("Print Report");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 575, 250, -1));

        lblRecordCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecordCount.setText("RECORD(S): 0");
        add(lblRecordCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 545, 250, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/searchIcon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 3, 100, -1));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        txtSearch.setText(txtSearch.getText().toUpperCase());
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        refreshCustomerTable(SearchController.getInstance().findBySearchCriteriaLocationAndMode(txtSearch.getText(), UISetting.getStoreLocation().getFinStartCode(), 2));
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.selectAll();
    }//GEN-LAST:event_txtSearchFocusGained

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        CAFReportDlg reportDlg = new CAFReportDlg(null, true);
        UIMgr.centerToScreen(reportDlg);
        if (transactionForm != null) {
            reportDlg.setFormNo(transactionForm.getTxFormNo());
            PersonalInfo cm2 = PersonalInfoController.getInstance().findByFormNoAndPersonType(transactionForm.getTxFormNo(), "CM2");
            if (cm2 != null) {
                reportDlg.enabledCM2Option(true);
            } else {
                reportDlg.enabledCM2Option(false);
            }
        }
        reportDlg.setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        refreshCustomerTable(SearchController.getInstance().findBySearchCriteriaLocationAndMode(txtSearch.getText(), UISetting.getStoreLocation().getFinStartCode(), 2));
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private java.util.List<Customer> customers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRecordCount;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblTransactionForm;
    private java.util.List<TransactionForm> transactionForms;
    private javax.swing.JTextField txtSearch;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private int selectedIndex = 0;
    private Customer customer;
    private TransactionForm transactionForm;
    private MainPanel mainPanel;

    public void setMainPanel(MainPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public Customer getCustomer() {
        return customer;
    }

    public TransactionForm getTransactionForm() {
        return transactionForm;
    }

    public void setTransactionForm(TransactionForm transactionForm) {
        this.transactionForm = transactionForm;
        mainPanel.fillValue(this.transactionForm);
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
        if (this.customer != null) {
            refreshTransactionFormTable(SearchController.getInstance().findByClientNo(this.customer.getClientNo()));
        }
    }

    public void refreshCustomerTable(List<Customer> c) {
        customers.clear();
        customers.addAll(c);
        if (!customers.isEmpty()) {
            lblRecordCount.setText("Search Result: " + customers.size());
            tblCustomer.setRowSelectionInterval(0, 0);
        }
        if (txtSearch.getText().equals("")) {
            txtSearch.setText("Search");
        }
    }

    public void refreshTransactionFormTable(List<TransactionForm> t) {
        transactionForms.clear();
        transactionForms.addAll(t);
        if (!transactionForms.isEmpty()) {
            tblTransactionForm.setRowSelectionInterval(0, 0);
        }
    }

    public void refresh() {
        refreshCustomerTable(SearchController.getInstance().findAllWithLimit(10));
    }
    
    public void enableSearch(boolean value) {
        txtSearch.setEnabled(value);
        btnSearch.setEnabled(value);
        tblCustomer.setEnabled(value);
        tblTransactionForm.setEnabled(value);
        btnPrint.setEnabled(value);
    }
}
