/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SummaryReportPanel.java
 *
 * Created on Aug 19, 2013, 1:18:39 PM
 */
package com.vg.scfc.financing.cis.ui.panel;

import com.vg.commons.dlg.WaitSplashScreen;
import com.vg.commons.listener.DoJasperPrintReport;
import com.vg.commons.util.StringUtils;
import com.vg.scfc.financing.cis.ui.settings.UISetting;
import com.vg.scfc.financing.cis.ui.validator.UIValidator;
import com.vg.scfc.financing.cis.value.SummaryReport;
import com.vg.scfc.financing.commons.ent.Location;
import com.vg.scfc.financing.commons.ent.ReportHeader;
import java.util.Date;
import java.util.List;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import org.slf4j.LoggerFactory;

/**
 *
 * @author raffy
 */
public class SummaryReportPanel extends javax.swing.JPanel implements DoJasperPrintReport {
    
    private String reportTitle = "";
    private List<Location> locations;
    private ReportHeader reportHeader;

    public void setReportHeader(ReportHeader reportHeader) {
        this.reportHeader = reportHeader;
    }
    
    private void setComponents() {
        cboBranch.removeAllItems();
        try {
            locations = UISetting.getLocationService().findAll();
            System.out.println(locations.size());
            for (Location location : locations) {
                cboBranch.addItem(location);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println(ex);
            UIValidator.log(ex, SummaryReportPanel.class);
        }
    }
    
    public void setDefault() {
        cboBranch.setSelectedItem(UISetting.getStoreLocation());
        cboReport.setSelectedIndex(0);
        txtFromDate.requestFocus();
    }

    /** Creates new form SummaryReportPanel */
    public SummaryReportPanel() {
        initComponents();
        setComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        try {
            txtFromDate = new com.vg.commons.formattedfields.FormattedSimpleDateField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        try {
            txtToDate = new com.vg.commons.formattedfields.FormattedSimpleDateField();
        } catch (java.text.ParseException e1) {
            e1.printStackTrace();
        }
        jLabel4 = new javax.swing.JLabel();
        cboBranch = new javax.swing.JComboBox();
        cboReport = new javax.swing.JComboBox();
        btnPrint = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Monospaced", 0, 10));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Branch:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Report:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setText("To");

        cboBranch.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cboBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboReport.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cboReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Summary of Applicants - ALL", "Summary of Applicants - APPROVED", "Summary of Applicants - DISAPPROVED", "Summary of Applicants - PENDING", "Summary of Forms" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboReport, 0, 267, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtToDate, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                            .addComponent(cboBranch, 0, 267, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
  new WaitSplashScreen(null, true, this, reportTitle).getThisDlg();
    }//GEN-LAST:event_btnPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cboBranch;
    private javax.swing.JComboBox cboReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.vg.commons.formattedfields.FormattedSimpleDateField txtFromDate;
    private com.vg.commons.formattedfields.FormattedSimpleDateField txtToDate;
    // End of variables declaration//GEN-END:variables

    private JasperPrint printSummary() {
        JasperPrint jasperPrint = null;
        try {
            
            Location location = (Location) cboBranch.getSelectedItem();
            Date fromDate = txtFromDate.getDate();
            Date toDate = txtToDate.getDate();

            switch(cboReport.getSelectedIndex()) {
                case 0:
                    reportTitle = "SUMMARY OF APPLICANTS - ALL";
                    jasperPrint = UISetting.getPrintReportService().
                            printApplicantSummary(location, fromDate, toDate,
                            SummaryReport.SUMMARY_APPLICANTS_ALL, UISetting.getReportHeader());
                    break;
                case 1:
                    reportTitle = "SUMMARY OF APPLICANTS - APPROVED";
                    jasperPrint = UISetting.getPrintReportService().
                            printApplicantSummary(location, fromDate, toDate,
                            SummaryReport.SUMMARY_APPLICANTS_APPROVED, UISetting.getReportHeader());
                    break;
                case 2:
                    reportTitle = "SUMMARY OF APPLICANTS - DISAPPROVED";
                    jasperPrint = UISetting.getPrintReportService().
                            printApplicantSummary(location, fromDate, toDate,
                            SummaryReport.SUMMARY_APPLICANTS_DISAPPROVED, UISetting.getReportHeader());
                    break;
                case 3:
                    reportTitle = "SUMMARY OF APPLICANTS - PENDING";
                    jasperPrint = UISetting.getPrintReportService().
                            printApplicantSummary(location, fromDate, toDate,
                            SummaryReport.SUMMARY_APPLICANTS_PENDING, UISetting.getReportHeader());
                    break;
                case 4:
                    reportTitle = "SUMMARY OF FORMS";
                    jasperPrint = UISetting.getPrintReportService().
                            printFormSummary(location, fromDate, toDate);
                    break;
            }
        } catch (Exception e) {
            LoggerFactory.getLogger(SummaryReportPanel.class).error(StringUtils.formatException(e));
        } finally {
            return jasperPrint;
        }
    }
    
    @Override
    public net.sf.jasperreports.engine.JasperPrint printNow() throws Exception {
        JasperPrint jasperPrint = printSummary();
        if(jasperPrint == null) 
            throw new Exception();
        else
            return jasperPrint;
    }
    
}
