/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vg.scfc.financing.cis.ui.reusable;

import com.vg.scfc.financing.cis.ent.Dependent;
import com.vg.scfc.financing.cis.ui.controller.CharacterReferenceDependentController;
import com.vg.scfc.financing.cis.ui.validator.UIValidator;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author rodel
 */
public class DependentPanel extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form DependentPanel
     */
    public DependentPanel() {
        initComponents();
        startUpSettings();
    }

    private void initTableDependent() {
        tableDependent.putClientProperty("Quaqua.Table.style", "striped");
        tableDependent.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableDependent.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                try {
                    selectedIndex = tableDependent.getSelectedRow();
                    if (selectedIndex >= 0) {
                        setDependent(dependents.get(selectedIndex));
                    }
                } catch (Exception e) {
                    UIValidator.log(e, CharacterReferenceDependentPanel.class);
                }
            }
        });
    }

    /**
     * Set TextBoxes KeyListener
     */
    private void initTextBoxesListener() {
        txtRefName.addKeyListener(this);
        txtRefAddress.addKeyListener(this);
        txtRefContact.addKeyListener(this);
        txtRefRelationship.addKeyListener(this);
    }

    private void startUpSettings() {
        setFieldsEditable(false);
        initTextBoxesListener();
        initTableDependent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dependents = ObservableCollections.observableList(new LinkedList<Dependent>());
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRefRelationship = new javax.swing.JTextField();
        txtRefContact = new javax.swing.JTextField();
        txtRefAddress = new javax.swing.JTextField();
        txtRefName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDependent = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 105, -1, -1));

        jLabel2.setText("Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, -1, -1));

        jLabel3.setText("Contact");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 155, -1, -1));

        jLabel4.setText("Relationship");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, -1, -1));

        txtRefRelationship.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefRelationshipFocusLost(evt);
            }
        });
        add(txtRefRelationship, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 175, 140, -1));

        txtRefContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefContactFocusLost(evt);
            }
        });
        add(txtRefContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        txtRefAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefAddressFocusLost(evt);
            }
        });
        add(txtRefAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 125, 255, -1));

        txtRefName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefNameFocusLost(evt);
            }
        });
        add(txtRefName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 255, -1));

        tableDependent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableDependent.setShowHorizontalLines(false);
        tableDependent.setShowVerticalLines(false);
        tableDependent.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, dependents, tableDependent);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${depName}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${depRelation}"));
        columnBinding.setColumnName("Relationship");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${depContactNo}"));
        columnBinding.setColumnName("Contact #");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tableDependent);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 600, 90));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRefRelationshipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefRelationshipFocusLost
        txtRefRelationship.setText(UIValidator.validate(txtRefRelationship));
    }//GEN-LAST:event_txtRefRelationshipFocusLost

    private void txtRefContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefContactFocusLost
        txtRefContact.setText(UIValidator.isNumeric(txtRefContact));
    }//GEN-LAST:event_txtRefContactFocusLost

    private void txtRefAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefAddressFocusLost
        txtRefAddress.setText(UIValidator.validate(txtRefAddress));
    }//GEN-LAST:event_txtRefAddressFocusLost

    private void txtRefNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefNameFocusLost
        txtRefName.setText(UIValidator.validate(txtRefName));
    }//GEN-LAST:event_txtRefNameFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Dependent> dependents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDependent;
    private javax.swing.JTextField txtRefAddress;
    private javax.swing.JTextField txtRefContact;
    private javax.swing.JTextField txtRefName;
    private javax.swing.JTextField txtRefRelationship;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private HeaderPanel headerPanel;
    private int selectedIndex = 0;
    private Dependent dependent;

    public void setDependent(Dependent dependent) {
        this.dependent = dependent;
        setDependentData(this.dependent);
    }

    public void setHeaderPanel(HeaderPanel headerPanel) {
        this.headerPanel = headerPanel;
    }

    public int getSelectedIndex() {
        return selectedIndex;
    }

    public void setSelectedIndex(int selectedIndex) {
        this.selectedIndex = selectedIndex;
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_TAB:
            case KeyEvent.VK_ENTER:
                if (txtRefName.isFocusOwner()) {
                    txtRefAddress.requestFocus();
                } else if (txtRefAddress.isFocusOwner()) {
                    txtRefContact.requestFocus();
                } else if (txtRefContact.isFocusOwner()) {
                    txtRefRelationship.requestFocus();
                }
                break;
            case KeyEvent.VK_UP:
                if (txtRefRelationship.isFocusOwner()) {
                txtRefContact.requestFocus();
            } else if (txtRefContact.isFocusOwner()) {
                txtRefAddress.requestFocus();
            } else if (txtRefAddress.isFocusOwner()) {
                txtRefName.requestFocus();
            }
                break;
        }
    }

    public void setFieldsEditable(boolean value) {
        txtRefName.setEditable(value);
        txtRefAddress.setEditable(value);
        txtRefContact.setEditable(value);
        txtRefRelationship.setEditable(value);

        txtRefName.setFocusable(value);
        txtRefAddress.setFocusable(value);
        txtRefContact.setFocusable(value);
        txtRefRelationship.setFocusable(value);
        tableDependent.setFocusable(value);

        if (value) {
            txtRefName.requestFocus();
        }
    }

    public void resetToDefault() {
        txtRefName.setText("");
        txtRefAddress.setText("");
        txtRefContact.setText("");
        txtRefRelationship.setText("");
    }

    public boolean saveDependent() {
        List<Dependent> d = CharacterReferenceDependentController.getInstance().addDependent(createNew(new Dependent()), headerPanel.getFormNo());
        refreshTableDependent(d);
        return !d.isEmpty();
    }

    public boolean updateDependent() {
        List<Dependent> d = CharacterReferenceDependentController.getInstance().updateDependent(headerPanel.getFormNo(), createNew(dependent));
        refreshTableDependent(d);
        return !d.isEmpty();
    }

    public void setDependentData(Object o) {
        if (o == null) {
            resetToDefault();
        } else {
            Dependent d = (Dependent) o;
            txtRefName.setText(d.getDepName());
            txtRefAddress.setText(d.getDepAddress());
            txtRefContact.setText(d.getDepContactNo());
            txtRefRelationship.setText(d.getDepRelation());
        }
    }

    public void refreshTableDependent(List<Dependent> d) {
        dependents.clear();
        dependents.addAll(d);
        if (!dependents.isEmpty()) {
            tableDependent.setRowSelectionInterval(0, 0);
        } else {
            resetToDefault();
        }
    }

    private Dependent createNew(Dependent d) {
        d.setDepName(txtRefName.getText());
        d.setDepAddress(txtRefAddress.getText());
        d.setDepContactNo(txtRefContact.getText());
        d.setDepRelation(txtRefRelationship.getText());
        return d;
    }
}
